server:
  port: 8088

spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Naeem152002/micro-configuration-service
          clone-on-start: true
   